name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t achu2002/comingle-server:latest .

      - name: Push Docker image to Docker Hub
        run: docker push achu2002/comingle-server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    
    steps: 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove all Docker images
        run: docker rmi -f $(docker images -q) || true

      - name: Pull image from Docker Hub
        run: docker pull achu2002/comingle-server:latest

      - name: Stop old container
        run: docker stop comingle-server-container || true

      - name: Delete old container
        run: docker rm comingle-server-container || true

      - name: Run new Docker container
        run: docker run -d --env-file /home/ubuntu/comingle/secrets/.env -p 5000:5000 --name comingle-server-container achu2002/comingle-server:latest

      - name: Restart Nginx
        run: sudo systemctl restart nginx
