name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t achu2002/comingle-server .
      - name: Publish image to docker hub
        run: docker push achu2002/comingle-server:latest
        
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull achu2002/comingle-server:latest
      - name: Delete old container
        run: docker rm -f comingle-server-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name comingle-server-container achu2002/comingle-server